"use client";

import { useMemo, useState } from "react";
import { App, Badge, Button, Drawer, Dropdown, Input, Select, Slider, Tag, message } from "antd";
import { BookOutlined, CalendarOutlined, DeleteOutlined, HeartOutlined, MenuOutlined, SearchOutlined, ShoppingOutlined, StarFilled, UserOutlined } from "@ant-design/icons";
import { books, categories, formatCurrency } from "@/lib/books";
import { useCartStore } from "@/store/cart-store";
import styles from "./page.module.css";

export default function Home() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Tất cả");
  const [maxPrice, setMaxPrice] = useState(20000);
  const [cartOpen, setCartOpen] = useState(false);
  const { items, addItem, removeItem, setDays } = useCartStore();
  const visibleBooks = useMemo(() => books.filter((book) => `${book.title} ${book.author}`.toLowerCase().includes(query.toLowerCase()) && (category === "Tất cả" || book.category === category) && book.pricePerDay <= maxPrice), [category, maxPrice, query]);
  const total = items.reduce((sum, item) => sum + item.pricePerDay * item.days, 0);
  const handleAdd = (book: (typeof books)[number]) => { if (items.some((item) => item.id === book.id)) { setCartOpen(true); return; } addItem(book); message.success(`${book.title} đã được thêm vào giỏ thuê`); };

  return <App><div className={styles.page}>
    <header className={styles.header}><div className={styles.headerInner}><a className={styles.brand} href="#top"><span className={styles.brandMark}><BookOutlined /></span><span>book<span>Nest</span></span></a><nav className={styles.nav}><a className={styles.activeLink} href="#books">Khám phá</a><a href="#how-it-works">Cách hoạt động</a><a href="#about">Về BookNest</a></nav><div className={styles.headerActions}><Button className={styles.iconButton} type="text" icon={<HeartOutlined />} /><Dropdown menu={{ items: [{ key: "login", label: <a href="/login">Đăng nhập</a> }, { key: "register", label: <a href="/register">Đăng ký tài khoản</a> }] }} placement="bottomRight"><Button className={styles.accountButton} type="text" icon={<UserOutlined />}>Tài khoản</Button></Dropdown><Badge count={items.length} size="small"><Button className={styles.cartButton} icon={<ShoppingOutlined />} onClick={() => setCartOpen(true)}>Giỏ thuê</Button></Badge></div><Button className={styles.mobileMenu} type="text" icon={<MenuOutlined />} /></div></header>
    <main id="top"><section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>Đọc nhiều hơn. Sống sâu hơn.</p><h1>Một thư viện nhỏ<br /><em>cho những ngày lớn.</em></h1><p className={styles.heroText}>Thuê những cuốn sách bạn muốn đọc, chỉ trong vài phút. Không cần mua cả tủ sách để bắt đầu một hành trình mới.</p><Button className={styles.heroButton} type="primary" href="#books">Khám phá bộ sưu tập <span>↗</span></Button><div className={styles.heroNote}><div className={styles.avatarStack}><span>LN</span><span>MT</span><span>KA</span></div><span>Hơn 2,000 độc giả đang đọc cùng BookNest</span></div></div><div className={styles.heroVisual}><div className={styles.sunShape} /><div className={styles.heroCard}><div className={styles.bookSpine}>BOOK<br />NEST</div><div className={styles.heroBook}><span>THE<br /><strong>ART</strong><br />OF<br />SLOW<br />LIVING</span></div><div className={styles.heroLabel}>Gợi ý hôm nay<br /><strong>Đọc chậm, sống đầy</strong></div></div><div className={styles.floatingQuote}>“Reading is a way<br />of travelling without<br />moving your feet.”</div></div></section>
      <section className={styles.catalog} id="books"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Bộ sưu tập được tuyển chọn</p><h2>Chọn một cuốn cho <em>hôm nay.</em></h2></div><span className={styles.resultCount}>{visibleBooks.length} cuốn sách</span></div><div className={styles.catalogLayout}><aside className={styles.filters}><div className={styles.filterTitle}>Bộ lọc <button onClick={() => { setCategory("Tất cả"); setMaxPrice(20000); setQuery(""); }}>Đặt lại</button></div><label className={styles.filterLabel}>Thể loại</label><div className={styles.categoryList}>{categories.map((item) => <button className={category === item ? styles.selectedCategory : ""} key={item} onClick={() => setCategory(item)}>{item}<span>{item === "Tất cả" ? books.length : books.filter((book) => book.category === item).length}</span></button>)}</div><label className={styles.filterLabel}>Giá thuê mỗi ngày</label><Slider min={5000} max={20000} step={1000} value={maxPrice} onChange={setMaxPrice} tooltip={{ formatter: (value) => formatCurrency(value ?? maxPrice) }} /><div className={styles.priceRange}><span>5.000đ</span><span>20.000đ</span></div><div className={styles.filterTip}><CalendarOutlined /><span>Tất cả sách được giao trong 24 giờ.</span></div></aside><div className={styles.results}><div className={styles.searchRow}><Input className={styles.searchInput} size="large" prefix={<SearchOutlined />} placeholder="Tìm theo tên sách hoặc tác giả..." value={query} onChange={(event) => setQuery(event.target.value)} /><Select className={styles.sortSelect} size="large" defaultValue="popular" options={[{ value: "popular", label: "Phổ biến nhất" }, { value: "price", label: "Giá thấp nhất" }]} /></div><div className={styles.bookGrid}>{visibleBooks.map((book) => <article className={styles.bookCard} key={book.id}><div className={styles.coverWrap} style={{ backgroundColor: book.accent }}><img src={book.cover} alt={book.title} /><button className={styles.favorite}><HeartOutlined /></button>{book.featured && <Tag className={styles.featuredTag}>Nổi bật</Tag>}</div><div className={styles.bookInfo}><div className={styles.bookMeta}><span>{book.category}</span><span><StarFilled /> {book.rating}</span></div><h3>{book.title}</h3><p>{book.author}</p><div className={styles.cardFooter}><div><strong>{formatCurrency(book.pricePerDay)}</strong><small> / ngày</small></div><Button className={styles.addButton} type="primary" onClick={() => handleAdd(book)} icon={<ShoppingOutlined />}>Thuê</Button></div></div></article>)}</div>{visibleBooks.length === 0 && <div className={styles.emptyState}>Không tìm thấy sách phù hợp. Hãy thử bộ lọc khác.</div>}</div></div></section>
      <section className={styles.impact} id="how-it-works"><div><p className={styles.eyebrow}>BookNest khác biệt</p><h2>Đọc theo nhịp<br /><em>của riêng bạn.</em></h2></div><div className={styles.impactItems}><div><span>01</span><h3>Chọn sách</h3><p>Lựa chọn từ bộ sưu tập được tuyển chọn bởi những người yêu sách.</p></div><div><span>02</span><h3>Thuê linh hoạt</h3><p>Thuê từ 3 đến 30 ngày, gia hạn dễ dàng khi bạn chưa muốn chia tay.</p></div><div><span>03</span><h3>Trả lại nhẹ nhàng</h3><p>Chúng tôi nhận sách tận nơi, để bạn luôn có chỗ cho cuốn tiếp theo.</p></div></div></section>
    </main>
    <Drawer title={<div className={styles.drawerTitle}><span>Giỏ thuê của bạn</span><small>{items.length} cuốn</small></div>} placement="right" width={420} open={cartOpen} onClose={() => setCartOpen(false)} footer={items.length ? <div className={styles.drawerFooter}><div><span>Tạm tính</span><strong>{formatCurrency(total)}</strong></div><Button type="primary" block size="large">Tiếp tục thuê <span>→</span></Button></div> : null}><div className={styles.cartList}>{items.length === 0 ? <div className={styles.emptyCart}><ShoppingOutlined /><h3>Giỏ thuê đang trống</h3><p>Thêm một cuốn sách để bắt đầu hành trình.</p></div> : items.map((item) => <div className={styles.cartItem} key={item.id}><img src={item.cover} alt="" /><div><strong>{item.title}</strong><small>{formatCurrency(item.pricePerDay)} / ngày</small><div className={styles.daysControl}><span>Số ngày</span><Select size="small" value={item.days} onChange={(value) => setDays(item.id, value)} options={[3, 7, 14, 30].map((days) => ({ value: days, label: `${days} ngày` }))} /></div></div><Button type="text" icon={<DeleteOutlined />} onClick={() => removeItem(item.id)} /></div>)}</div></Drawer>
  </div></App>;
}
